### ISSUE TITLE
peerDependencies babel-core

### ISSUE THREAD

**Issue by mysticatea** [twada/babel-plugin-espower#1]
Hello, thanks for the great plugin!

But, I was surprised to be added a dependency `babel-core` to my `package.json`.

`peerDependencies` will not install the packages automatically since npm version 3, and I guess that most users have installed `babel`, not `babel-core`.
So this setting might trouble users.

I think that `dependencies` should be used instead of `peerDependencies`, or `babel` should be used instead of `babel-core` in `peerDependencies`.

Thanks!

**Comment by twada** [comment]
@mysticatea Hi, thank you for using babel-plugin-espower!

> peerDependencies will not install the packages automatically since npm version 3
> 

I know, I know, I don't want to use `peerDependencies`...

The reason why I use `peerDependencies` is due to the [strict type checking in babel transformer](https://github.com/babel/babel/blob/v5.1.10/src/babel/transformation/transformer.js#L73-L75).

(Same solution as: [Transformer plugins cannot be extracted as separate modules · Issue #1162 · babel/babel](https://github.com/babel/babel/issues/1162))

The problem is that all plugins should use the same babel (or babel-core) instance.

```
your-project
└── node_modules
    ├── babel-plugin-1
    │   └── node_modules
    │       └── babel-core
    └── babel-plugin-2
        └── node_modules
            └── babel-core
```

Wont work.

```
your-project
└── node_modules
    ├── babel-core
    ├── babel-plugin-1
    └── babel-plugin-2
```

Will work.


> I guess that most users have installed babel, not babel-core.
> I think that dependencies should be used instead of peerDependencies, or babel should be used instead of babel-core in peerDependencies.

Your suggestion makes sense!

I'll try adding `"babel": "^5.0.0"` as `peerDependencies` and see what happens.

**Comment by mysticatea** [comment]
Oops, `instanceof` operator!! It's a... very difficult obstacle.

In fact, I sometimes met with the error, and I understood that it's fixed when re-installed dependencies.

In one of my cases, I'm using one of `babel` and `babelify` depending on the context.
Ummm...

I tried.

```js
var item = module;
while (item != null) {
  console.log(item.id);
  item = item.parent;
}
```

```
C:\\(省略)\\node_modules\\babel-plugin-espower\\index.js
C:\\(省略)\\node_modules\\babel-core\\lib\\babel\\transformation\\file\\index.js
C:\\(省略)\\node_modules\\babel-core\\lib\\babel\\transformation\\transformer.js
C:\\(省略)\\node_modules\\babel-core\\lib\\babel\\transformation\\index.js
C:\\(省略)\\node_modules\\babel-core\\lib\\babel\\api\\node.js
C:\\(省略)\\node_modules\\babel-core\\lib\\babel\\api\\register\\node.js
C:\\(省略)\\node_modules\\babel-core\\register.js
C:\\(省略)\\node_modules\\babel\\register.js
C:\\(省略)\\mocha-babel-hook.js
.
```

We can get the modules that requires me first via `module.parent`. (Or to enumerate the `require.cache` object.)
It probably contain files of `babel-core`. 
If found, the value of `item.exports` property is one we want.
Otherwise, use `require("babel-core")` normally.

But, this way is weak in file structure changes. 
It's bad.

**Comment by twada** [comment]
Thanks @mysticatea, I've added [a little explanation](https://github.com/twada/babel-plugin-espower#faq-why-peerdependencies-why-npm-dedupe) to README.

**Comment by mysticatea** [comment]
Thanks!
It's enough to me.

**Comment by shuhei** [comment]
I haven't tested it by myself but it seems like [the current version of babel checks the name of constructor instead of `instanceof`](https://github.com/babel/babel/blob/v5.2.16/src/babel/transformation/file/plugin-manager.js#L57). I guess `babel-core` can be moved into `dependencies` now.

**Comment by shuhei** [comment]
Ah, no. Please forget it. It's [still checking `instanceof`](https://github.com/babel/babel/blob/v5.2.16/src/babel/transformation/transformer.js#L89).

**Comment by twada** [comment]
@shuhei Thanks, no problem! Please tell me again if there's any progress on this issue.

**Comment by twada** [comment]
@shuhei FYI: It seems that [babel 5.2.0+ API introduces shared babel-core as an plugin argument](https://github.com/sebmck/babel-plugin-example/pull/1/files). This will fix the entire problem!

**Comment by shuhei** [comment]
Wow, it's neat. Thanks a lot!
