### ISSUE TITLE
Unknown node type Super.

### ISSUE THREAD

**Issue by mysticatea** [twada/babel-plugin-espower#2]
Hello!

I got an error `Unknown node type Super.`.
Maybe, an issue about combination of `CallExpression` and `Super`?

```js
// test.js
class Hoge extends Object {
  constructor() {
    super();
  }
}
```

```
$ babel test.js --plugins babel-plugin-espower
```

```
C:\~~\node_modules\babel-core\lib\babel\helpers\parse.js:70
    throw err;
          ^
Error: test.js: Unknown node type Super.
    at Controller.traverse (C:\~~\node_modules\babel-plugin-espower\node_modules\escallmatch\node_modules\estraverse\estraverse.js:513:31)
    at Object.traverse (C:\~~\node_modules\babel-plugin-espower\node_modules\escallmatch\node_modules\estraverse\estraverse.js:705:27)
    at isSameAstDepth (C:\~~\node_modules\babel-plugin-espower\node_modules\escallmatch\index.js:110:16)
...
```

Versions:

- babel: `5.1.11`
- babel-core: `5.1.11`
- babel-plugin-espower: `0.2.1`

Thanks!

**Comment by mysticatea** [comment]
Hm, this issue seems to be on estraverse.

- `Super` on ESTree. - https://github.com/estree/estree/blob/e5b93db15b429aba0cb1b823fc3352b4496e6996/es6.md#expressions
- `Super` on Esprima - https://github.com/jquery/esprima/blob/deef03ca006b03912d9f74b041f9239a9045181f/esprima.js#L164
- `Super` on Babel - https://github.com/babel/babel/blob/c9518bb60d45d741ecab5dcc354f432005bfe69b/src/babel/types/alias-keys.json#L73
- `SuperExpression` on estraverse - https://github.com/estools/estraverse/blob/166ebbe0a8d45ceb2391b6f5ef5d1bab6bfb267a/estraverse.js#L199

**Comment by azu** [comment]
Related: https://github.com/estools/escope/issues/58

**Comment by twada** [comment]
I saw [Change Super interface by azu · Pull Request #48 · estools/estraverse](https://github.com/estools/estraverse/pull/48) lands. Now looking for a new release of estraverse. Thank you so much @azu !!

**Comment by azu** [comment]
[estraverse 4.0.0](https://github.com/estools/estraverse/releases/tag/4.0.0 "4.0.0") is released.

**Comment by twada** [comment]
@azu  :tada: 
Okay I'll take the major bump in.

**Comment by twada** [comment]
@mysticatea Sorry for my late response. I've just [released v0.2.2](https://github.com/twada/babel-plugin-espower/releases/tag/v0.2.2), so please check it out.

**Comment by mysticatea** [comment]
Yay, thank you @twada, @azu!  
I got the fix!

**Comment by twada** [comment]
@mysticatea Thank you for reporting!
